baseURL = "https://jesusxy.github.io/project-trinity/"
languageCode = "en-us"
title = "project trinity"
theme = "trinity"

[params]
  description = "Project Trinity is an independent security research archive focused on malware analysis, systems security, adversarial infrastructure, and the art of cyberwarfare."

[menu]
  [[menu.main]]
    name = "canon"
    url = "/canon/"
    weight = 1
  [[menu.main]]
    name = "labs"
    url = "/labs/"
    weight = 2
  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 3
